[package]
name = "cargo-wipe"
version = "0.1.2"
edition = "2018"
license = "MIT"
authors = ["Mihai Dinculescu <mihai.dinculescu@iotic-labs.com>"]
description = "recursively wipe target and node_modules folders"
keywords = ["cli", "cargo", "wipe", "target", "node_modules"]
categories = ["command-line-interface", "command-line-utilities"]
readme = "README.md"
repository = "https://github.com/mihai-dinculescu/cargo-wipe"

[dependencies]
structopt = "0.3.14"
yansi = "0.5.0"
num-format = "0.4.0"
anyhow = "1.0.31"
