name: Rust

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: davidB/rust-cargo-make@v1
      - uses: actions/checkout@v2
      - name: Run format
        run: cargo make format
      - name: Run check
        run: cargo make check
      - name: Run clippy
        run: cargo make clippy
      - name: Run test
        run: cargo make test
